[project]
name = "final-project-se333-simrankaur"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.13.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.0",
]
